version: '3'

services:
  postgresSQL:
    image: postgres
    environment:
      POSTGRES_USERNAME: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - postgres-compose-network
      

networks: 
  postgres-compose-network:
    driver: bridge